package main

func main() {
	// loop.Looping()
	// variable.Variables()
	// exercises.ExerciseOne()
	// exercises.ExerciseTwo()
	// exercises.ExerciseThree()
	// exercises.ExerciseFour()
	// exercises.ExerciseFive()
	// exercises.ExerciseSix()
	// exercises.ExerciseSeven()
	// exercises.ExerciseEight()
	// exercises.ExerciseNine()
	// exercises.ExerciseTen()
	// codewars.HighAndLow("1 1 98 34 21 -1")
	// codewars.Disemvowel("This website is for losers LOL!")
	// codewars.GetCount("Gabriela Lacerda")
	// codewars.EvenOrOdd(11)
	// codewars.Scale("abcd\nefgh\nijkl\nmnop", 2, 3)
	// codewars.Digitize(987654)
	// flowcontrol.FlowControl()
	// flowcontrol.SwitchCase()
	// strgs.StringRune()
	// slice.SliceTest()
	// strct.StructsGo()
	// functionsgo.MainSoma()
	// functionsgo.Anonymous()
	// functionsgo.MainFunctions()
	// pointers.PointerTest()
	// applications.DocJson()
	// applications.DocJsonUnmarshal()
}
